"""
Crop Disease Prediction Pipeline
Image → YOLOv8 Detection → Result (disease info loaded dynamically from JSON)
"""

import cv2
import numpy as np
import json
import time
from pathlib import Path
from ultralytics import YOLO
from typing import Any

# ── Load models (Lazy) ─────────────────────────────────
YOLO_MODEL: Any = None
DISEASE_INFO: dict = {}

def load_models():
    global YOLO_MODEL, DISEASE_INFO
    if YOLO_MODEL is None:
        print("Loading YOLO model into memory...")
        YOLO_MODEL = YOLO("models/yolov8_custom.pt")

        # Load disease info from JSON (generated by download script)
        info_path = Path("models/disease_info.json")
        if info_path.exists():
            with open(info_path, "r") as f:
                DISEASE_INFO = json.load(f)
            print(f"✅ Loaded disease info for {len(DISEASE_INFO)} classes")
        else:
            print("⚠️  disease_info.json not found — using minimal fallback")

def get_disease_info(class_name: str) -> dict:
    """
    Dynamic lookup: first tries exact match, then tries fuzzy match
    by trimming underscores/spaces from the class label.
    Falls back to a clean auto-generated message based on class label parsing.
    """
    # Direct match
    if class_name in DISEASE_INFO:
        return DISEASE_INFO[class_name]

    # Try normalised match (e.g. "Tomato Early blight" → "Tomato___Early_blight")
    normalised = class_name.replace(" ", "_")
    for key in DISEASE_INFO:
        if key.replace("___", "_").lower() == normalised.replace("___", "_").lower():
            return DISEASE_INFO[key]

    # Auto-generate from class name format "Crop___Disease"
    parts = class_name.replace("___", "|||").replace("__", "|||").split("|||")
    crop    = parts[0].replace("_", " ").strip() if len(parts) > 0 else "Unknown Crop"
    disease = parts[1].replace("_", " ").strip() if len(parts) > 1 else class_name.replace("_", " ")

    if "healthy" in disease.lower():
        return {
            "severity": "None",
            "description": f"{crop} plant appears healthy — no disease detected.",
            "treatment": "Continue standard monitoring and balanced fertilization schedule."
        }

    return {
        "severity": "Unknown",
        "description": f"{disease} detected on {crop} plant.",
        "treatment": f"Isolate affected plants and consult a local agronomist for a targeted {disease} treatment plan on {crop}."
    }


def draw_results(img, boxes, class_name, conf):
    """Draw bounding boxes and labels on image."""
    annotated = img.copy()
    for box in boxes:
        x1, y1, x2, y2 = map(int, box)
        cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 80), 2)
        label = f"{class_name.replace('_', ' ')} {conf:.1f}%"
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(annotated, (x1, y1-22), (x1+tw+6, y1), (0, 255, 80), -1)
        cv2.putText(annotated, label, (x1+3, y1-5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 2)
    return annotated


def predict(image_path: str, save_result: bool = True) -> dict:
    """
    Full pipeline: Image → YOLO → Result dict with dynamic disease info.
    """
    load_models()
    start = time.time()
    img_path = Path(image_path)
    img = cv2.imread(str(img_path))
    if img is None:
        raise ValueError(f"Cannot read image: {image_path}")
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # ── YOLO Detection ─────────────────────────────────
    assert YOLO_MODEL is not None
    # Higher threshold to avoid weak false-positive detections
    yolo_results = YOLO_MODEL(img_rgb, conf=0.50, iou=0.45, verbose=False)
    boxes = []
    yolo_conf = 0.0
    best_class_idx = 0

    for r in yolo_results:
        r_boxes: Any = r.boxes
        if r_boxes is not None and len(r_boxes) > 0:
            for box in r_boxes:
                boxes.append(box.xyxy[0].cpu().numpy())
                conf = float(box.conf[0])
                if conf > yolo_conf:
                    yolo_conf = conf
                    best_class_idx = int(box.cls[0])

    # Find the "healthy" class index for the detected crop (fallback)
    def find_healthy_class() -> str:
        for name in YOLO_MODEL.names.values():
            if "healthy" in name.lower():
                return name
        return list(YOLO_MODEL.names.values())[0]

    if boxes:
        confidence = yolo_conf * 100.0
        class_name = YOLO_MODEL.names[best_class_idx]
        # Guard: if confidence is below 55%, the model is uncertain — call it healthy
        if confidence < 55.0:
            class_name = find_healthy_class()
            confidence = 100.0 - confidence  # flip: express as "healthy confidence"
    else:
        confidence = 0.0
        class_name = find_healthy_class()  # No detection → healthy

    # ── Dynamic disease info lookup ─────────────────────
    info = get_disease_info(class_name)
    elapsed = float(f"{(time.time() - start) * 1000:.1f}")

    # Determine crop type from class name prefix
    crop = class_name.split("___")[0].replace("_", " ") if "___" in class_name else "Unknown"

    result = {
        "image_path"  : str(img_path),
        "crop_type"   : crop,
        "disease_name": class_name.replace("___", " — ").replace("_", " "),
        "confidence"  : float(f"{confidence:.2f}"),
        "severity"    : info["severity"],
        "description" : info["description"],
        "treatment"   : info["treatment"],
        "yolo_boxes"  : len(boxes),
        "inference_ms": elapsed,
        "top5"        : [{"class": class_name.replace("_", " "), "prob": float(f"{confidence:.2f}")}]
    }

    # ── Annotate and save result image ──────────────────
    out_path = Path("app/static/results") / f"result_{img_path.stem}.jpg"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if save_result:
        if boxes:
            annotated = draw_results(img, boxes, class_name, confidence)
        else:
            annotated = img.copy()
            cv2.putText(annotated, "No detection", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 200, 255), 2)
        cv2.imwrite(str(out_path), annotated)
        result["result_image"] = str(out_path)

    return result


if __name__ == "__main__":
    import sys
    test_image = sys.argv[1] if len(sys.argv) > 1 else "test_leaf.jpg"
    r = predict(test_image)
    print("\n🔬 DETECTION RESULT")
    print(f"   Disease   : {r['disease_name']}")
    print(f"   Crop      : {r['crop_type']}")
    print(f"   Confidence: {r['confidence']}%")
    print(f"   Severity  : {r['severity']}")
    print(f"   Treatment : {r['treatment']}")
    print(f"   Time      : {r['inference_ms']} ms")